/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Toolkit;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Cria novo formulario da classe Principal
     */
    public Principal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/OSSOicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areadetrab = new javax.swing.JDesktopPane();
        nomeUsuario = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        textoTipouser = new javax.swing.JLabel();
        barramenu = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemOS = new javax.swing.JMenuItem();
        itemUsuarios = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemServicos = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OSSO");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        areadetrab.setBackground(new java.awt.Color(255, 255, 255));
        areadetrab.setName(""); // NOI18N
        areadetrab.setPreferredSize(new java.awt.Dimension(737, 443));

        javax.swing.GroupLayout areadetrabLayout = new javax.swing.GroupLayout(areadetrab);
        areadetrab.setLayout(areadetrabLayout);
        areadetrabLayout.setHorizontalGroup(
            areadetrabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        areadetrabLayout.setVerticalGroup(
            areadetrabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        nomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomeUsuario.setText("usuario");

        data.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        data.setText("data");
        data.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        textoTipouser.setText("tipo-de-usuario");
        textoTipouser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        menuOpcoes.setText("Opções");

        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(itemSair);

        barramenu.add(menuOpcoes);

        menuCadastro.setText("Cadastro");

        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(itemClientes);

        itemOS.setText("Ordem de Serviço");
        itemOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOSActionPerformed(evt);
            }
        });
        menuCadastro.add(itemOS);

        itemUsuarios.setText("Usuários do Sistema");
        itemUsuarios.setEnabled(false);
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(itemUsuarios);

        barramenu.add(menuCadastro);

        menuRelatorio.setText("Relatórios");
        menuRelatorio.setEnabled(false);

        itemServicos.setText("Serviços");
        menuRelatorio.add(itemServicos);

        barramenu.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemSobre);

        barramenu.add(menuAjuda);

        setJMenuBar(barramenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(textoTipouser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(data))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areadetrab, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areadetrab, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTipouser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUsuario)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {nomeUsuario, textoTipouser});

        setSize(new java.awt.Dimension(755, 536));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void itemOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOSActionPerformed
        /*Opção do menu Cadastro > Ordem de Serviço*/
        OS cad_os = new OS();
        cad_os.setVisible(true);
        areadetrab.add(cad_os);
    }//GEN-LAST:event_itemOSActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /*Formatação de Data e Hora na tela principal*/
        Date datas = new Date();
        DateFormat dataformatado = DateFormat.getDateTimeInstance();
        data.setText(dataformatado.format(datas));
    }//GEN-LAST:event_formWindowActivated

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        /*Opção do menu Opções > Sair*/
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair?","Sair",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        /*Opção do menu Ajuda > Sobre*/
        Sobre chamarsobre = new Sobre();
        chamarsobre.setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        /*Opção do menu Cadastro >  Usuários do Sistema*/
        Usuario cad_usuario = new Usuario();
        cad_usuario.setVisible(true);
        areadetrab.add(cad_usuario);
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        /*Opção do menu Cadastro > Clientes*/
        Cliente cad_cliente = new Cliente();
        cad_cliente.setVisible(true);
        areadetrab.add(cad_cliente);
    }//GEN-LAST:event_itemClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Cria e mostra o formulario */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areadetrab;
    private javax.swing.JMenuBar barramenu;
    private javax.swing.JLabel data;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemOS;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemServicos;
    private javax.swing.JMenuItem itemSobre;
    public static javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuOpcoes;
    public static javax.swing.JMenu menuRelatorio;
    public static javax.swing.JLabel nomeUsuario;
    public static javax.swing.JLabel textoTipouser;
    // End of variables declaration//GEN-END:variables
}
